spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sms_db
    username: postgres
    password: silicon
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
        show-sql: true
        format_sql: true

# Twilio configuration
twilio:
  accountSid: AC61b259eb289150ca9cdb2aaf4d8f51b4
  authToken: a9fa671cf4dc1a4266a6051f35ffab0a
  fromNumber: "+12137862316"

